config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       registrations: "users/registrations",
                     }
  root "items#index"
  
  resources :mypages do
    collection do
      get :mypage
      get :mypagelogout
      get :card
      get :exhibition
      get :trans
      get :complete
      get :negotiate
      get :purchased
      get :voucher
      get :sales
      get :point
    end
  end
  resources :users do
    collection do
      get :profile
    end
  end
  resources :user_steps, only: [:create]
  resources :user_steps do
    collection do
      get "register1"
      get "register2"
      get "register3"
      get "register4"
      get "done"
    end
  end
  resources :cards, only: [:new, :show] do
    collection do
      post "pay", to: "cards#pay"
      post "delete", to: "cards#delete"
    end
  end
  resources :items do
    collection do
      post "pay", to: "items#pay"
      get "stop"
      get "exhibition"
      get :search
    end
    member do
      get :pay_comfirm
      post "pay", to: "items#pay"
    end
    resources :comments, only: :create
  end
  resources :categories do
    collection do
      get :category
      get :category_root
      get :category_child
      get :category_grandchild
    end
  end
end

app/views/shared/_category.html.haml
.category__all
  %ul.category0s
    -@parents.each do |parent|
      =link_to category_root_categories_path(parent.id) do
        %li.category0
          =parent.name
          %ul.category1s
            -parent.children.each do |child|
              =link_to category_child_categories_path(child.id) do
                %li.category1
                  =child.name
                  %ul.category2s
                    -child.children.each do |grandchild|
                      =link_to category_grandchild_categories_path(grandchild.id) do
                        %li.category2
                          =grandchild.name

app/views/shared/_footer.html.haml
.footer__top
  = image_tag src="/images/footer.jpg",class: 'market'
  .footer__top__smartphone
    .footer__top__smartphone__left
      .footer__top__smartphone__left__text
        .footer__top__smartphone__left__text__text1
          スマホでかんたんフリマアプリ
        .footer__top__smartphone__left__text__text2
          今すぐ無料ダウンロード！
      .footer__top__smartphone__left__app
        .footer__top__smartphone__left__app__logo
          = image_tag src="/images/logo_red.svg",class: 'app_logo'
        .footer__top__smartphone__left__app__ios
          =image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/app-store-a5c17948c6fd6d5b60b13d421cd60b35.svg"
        .footer__top__smartphone__left__app__android
          =image_tag src="https://web-jp-assets.mercdn.net/_next/static/images/google-play-495575abb895b405aa6336b2a4304958.svg" 
    .footer__top__smartphone__right
      = image_tag src="/images/footer_right.png",class: 'smartphone'
.footer__bottom
  .footer__bottom__link
    .footer__bottom__link__about
      .footer__bottom__link__about__title
        メルカリについて
      %ul.footer__bottom__link__about__title__bullet
        %li.footer__bottom__link__about__title__bullet__item
          会社概要
      %ul.footer__bottom__link__about__title__bullet
        %li.footer__bottom__link__about__title__bullet__item
          採用情報
      %ul.footer__bottom__link__about__title__bullet
        %li.footer__bottom__link__about__title__bullet__item
          プレリリース
      .footer__bottom__link__about__sns
        .footer__bottom__link__about__sns__twitter
          = icon('fab', 'twitter')
        .footer__bottom__link__about__sns__facebook
          = icon('fab', 'facebook-square')
        
    .footer__bottom__link__help
      .footer__bottom__link__help__title
        ヘルプ＆ガイド
      %ul.footer__bottom__link__help__title__bullet
        %li.footer__bottom__link__help__title__bullet__item
          ガイド
      %ul.footer__bottom__link__help__title__bullet
        %li.footer__bottom__link__help__title__bullet__item
          ゆう便
      %ul.footer__bottom__link__help__title__bullet
        %li.footer__bottom__link__help__title__bullet__item
          安全について
    .footer__bottom__link__privacy
      .footer__bottom__link__privacy__title
        プライバシーと利用規約
      %ul.footer__bottom__link__privacy__title__bullet
        %li.footer__bottom__link__privacy__title__bullet__item
          プライバシーとポリシー
      %ul.footer__bottom__link__privacy__title__bullet
        %li.footer__bottom__link__privacy__title__bullet__item
          利用規約
    .footer__bottom__link__rule
      %ul.footer__bottom__link__rule__bullet
        %li.footer__bottom__link__rule__bullet__item
          個人データについて
      %ul.footer__bottom__link__rule__bullet
        %li.footer__bottom__link__rule__bullet__item
          特定商取引について
    .footer__bottom__link__country
      .footer__bottom__link__country__title
        国
      %ul.footer__bottom__link__country__title__bullet
        %li.footer__bottom__link__country__title__bullet__item
          日本
        %li.footer__bottom__link__country__title__bullet__item
          United States
  .footer__bottom__copyright
    .footer__bottom__copyright__logo
      = image_tag src="/images/fmarket_logo_white.svg",class: 'logowhite'
    .footer__bottom__copyright__text
      %small &copy;lumine Co.,Ltd.

app/views/shared/_header.html.haml
.header__top
  .header__top__logo
    =link_to root_path do
      = image_tag src="/images/fmarket_logo_red.svg",class: 'mercari'
  .header__top__search
    .header__top__search__text
      =search_form_for(@search,url: search_items_path) do |f|
        =f.search_field :name_cont_all,{class:"search_form",placeholder:"何かお探しですか？"}
        =f.label "" do
          =f.submit '',class:"search_button"
          .header__top__search__icon
            = icon('fas', 'search')
.header__bottom
  %ul.header__bottom__left
    %li.header__bottom__left__category
      =link_to category_categories_path do
        = icon('fas', 'list-ul',class:"list-ul")
        カテゴリーから探す
      = render 'shared/category'
    %li.header__bottom__left__brand
      = icon('fas', 'tag',class:"tag")
      ブランドから探す
  -if user_signed_in?
    .header__bottom__right
      .header__bottom__right__good
        .header__bottom__right__good__icon
        = icon('fas', 'heart',class:"heart")
        .header__bottom__right__good__text
          いいね！一覧
      .header__bottom__right__info
        .header__bottom__right__info__icon
        = icon('fas', 'bell',class:"bell")
        .header__bottom__right__info__text
          お知らせ
      .header__bottom__right__todo
        .header__bottom__right__todo__icon
        = icon('fas', 'check',class:"check")
        .header__bottom__right__todo__text
          やることリスト
      =link_to mypage_mypages_path do
        .header__bottom__right__my
          .header__bottom__right__my__icon
          = icon('fas', 'user',class:"user")
          .header__bottom__right__my__text
            マイページ
  -else
    .header__bottom__right
      =link_to '新規会員登録',new_user_path,class:"header__bottom__right__register"
      =link_to 'ログイン',new_user_session_path,class:"header__bottom__right__login"

app/views/shared/_logintop.html.haml
.header__top
  .header__top__logo
    =link_to root_path do
      = image_tag src="/images/fmarket_logo_red.svg",class: 'mercari'
  .header__top__search
    .header__top__search__text
      %input{name: "content", type:"text",class: "input",placeholder: '何かお探しですか？'}
      //検索実装時にフォームに変更してください。
    .header__top__search__icon
      = icon('fas', 'search')
.header__bottom
  .header__bottom__left
    .header__bottom__left__category
      = icon('fas', 'list-ul',class:"list-ul")
      カテゴリーから探す
      .category__all
        %li.category__li
          .category__title1.category-list
            カテゴリー１
          .category__item
            %ul.sub
              %li.category__sub1.category-list
                カテゴリー１.１
                %ul.subsub
                  %li.category__subsub1.category-list
                    カテゴリー１.１.1
                  %li.category__subsub2
                    カテゴリー１.1.2
              %li.category__sub2
                カテゴリー１.2

        %li.category__li
          .category__title2
            カテゴリー2
          -# .category__item
          -#   %ul.category__li
          -#     %li.category__sub
          -#       カテゴリー2.１
          -#     %li.category__sub
          -#       カテゴリー2.2

    .header__bottom__left__brand
      = icon('fas', 'tag',class:"tag")
      ブランドから探す
      %ul.brand__all
        %li.brand
          brand1
        %li.brand
          brand2
    
  .header__bottom__right
    .header__bottom__right__good
      .header__bottom__right__good__icon
      = icon('fas', 'heart',class:"heart")
      .header__bottom__right__good__text
        いいね！一覧
    .header__bottom__right__info
      .header__bottom__right__info__icon
      = icon('fas', 'bell',class:"bell")
      .header__bottom__right__info__text
        お知らせ
    .header__bottom__right__todo
      .header__bottom__right__todo__icon
      = icon('fas', 'check',class:"check")
      .header__bottom__right__todo__text
        やることリスト
    =link_to mypage_mypages_path do
      .header__bottom__right__my
        .header__bottom__right__my__icon
        = icon('fas', 'user',class:"user")
        .header__bottom__right__my__text
          マイページ