config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       registrations: "users/registrations",
                     }
  root "items#index"
  
  resources :mypages do
    collection do
      get :mypage
      get :mypagelogout
      get :card
      get :exhibition
      get :trans
      get :complete
      get :negotiate
      get :purchased
      get :voucher
      get :sales
      get :point
    end
  end
  resources :users do
    collection do
      get :profile
    end
  end
  resources :user_steps, only: [:create]
  resources :user_steps do
    collection do
      get "register1"
      get "register2"
      get "register3"
      get "register4"
      get "done"
    end
  end
  resources :cards, only: [:new, :show] do
    collection do
      post "pay", to: "cards#pay"
      post "delete", to: "cards#delete"
    end
  end
  resources :items do
    collection do
      post "pay", to: "items#pay"
      get "stop"
      get "exhibition"
      get :search
    end
    member do
      get :pay_comfirm
      post "pay", to: "items#pay"
    end
    resources :comments, only: :create
  end
  resources :categories do
    collection do
      get :category
      get :category_root
      get :category_child
      get :category_grandchild
    end
  end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :set_card
  before_action :set_category
  before_action :set_ransack

  def mypage
    @items = Item.where(user_id: current_user.id)
  end

  def mypagelogout
  end

  def card
  end

  def exhibition
    @exhibitions = Item.where(status: [:exhibition, :stop]).where(user_id: current_user.id).order(id: "DESC").page(params[:page]).per(10)
  end

  def trans
    @transes = Item.where(status: :trans).where(user_id: current_user.id).order(id: "DESC").page(params[:page]).per(10)
  end

  def complete
    @completes = Item.where(status: :complete).where(user_id: current_user.id).order(id: "DESC").page(params[:page]).per(10)
  end

  def negotiate
    # 「コメント入力した商品」に変更
    @negotiate_items = Item.where(status: :trans).where(buyer: current_user.id).order(id: "DESC").page(params[:page]).per(10)
  end

  def purchased
    @bought_items = Item.where(buyer: current_user.id).order(id: "DESC").page(params[:page]).per(10)
  end

  def voucher
    @used_vouchers = UsedVoucherUser.where(user_id: current_user)
    @used_vouchers_mat = @used_vouchers.map { |record| record.voucher_id }
    @vouchers = Voucher.where.not(id: @used_vouchers_mat)
  end

  def sales
    @items=Item.where(user_id:current_user.id).where(status: :complete)
    @sales=0
    @items.each do |item|
      @sales+=item.price
    end
  end

  private

  def set_card
    @card = Card.where(user_id: current_user.id).first
  end

  def set_category
    @parents = Category.order("id ASC").limit(3)
  end

  def set_ransack
    @search = Item.ransack(params[:q])
    @items = @search.result.page(params[:page]).per(16)
  end
end

app/views/mypages/_left.html.haml
.contents-mypage__left__lists
  %ul.contents-mypage__left__lists__mypagelist
    =link_to mypage_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          マイページ
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    %li.contents-mypage__left__lists__mypagelist__tag
      .contents-mypage__left__lists__mypagelist__tag__text
        お知らせ
      .contents-mypage__left__lists__mypagelist__tag__icon
        = icon('fas', 'angle-right',class:"angle")
    %li.contents-mypage__left__lists__mypagelist__tag
      .contents-mypage__left__lists__mypagelist__tag__text
        やることリスト
      .contents-mypage__left__lists__mypagelist__tag__icon
        = icon('fas', 'angle-right',class:"angle")
    %li.contents-mypage__left__lists__mypagelist__tag
      .contents-mypage__left__lists__mypagelist__tag__text
        いいね
      .contents-mypage__left__lists__mypagelist__tag__icon
        = icon('fas', 'angle-right',class:"angle")
    =link_to new_item_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          出品する
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to exhibition_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          出品した商品-出品中
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to trans_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          出品した商品-取引中
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to complete_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          出品した商品-売却済み
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to negotiate_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          購入した商品-取引中
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to purchased_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          購入した商品-過去の取引
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    .contents-mypage__left__lists__mypagelist__title
      メルペイ
  %ul.contents-mypage__left__lists__mypagelist
    =link_to sales_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          売り上げ
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to point_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          ポイント
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to voucher_mypages_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          クーポン
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    .contents-mypage__left__lists__mypagelist__title
      設定
  %ul.contents-mypage__left__lists__mypagelist
    =link_to profile_users_path do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          プロフィール
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    -if @card.present?
      =link_to card_path(@card) do
        %li.contents-mypage__left__lists__mypagelist__tag
          .contents-mypage__left__lists__mypagelist__tag__text
            支払い方法
          .contents-mypage__left__lists__mypagelist__tag__icon
            = icon('fas', 'angle-right',class:"angle")
    -else
      =link_to card_mypages_path do
        %li.contents-mypage__left__lists__mypagelist__tag
          .contents-mypage__left__lists__mypagelist__tag__text
            支払い方法
          .contents-mypage__left__lists__mypagelist__tag__icon
            = icon('fas', 'angle-right',class:"angle")
    =link_to edit_user_path(current_user) do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          本人情報
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")
    =link_to mypagelogout_mypages_path(current_user.id) do
      %li.contents-mypage__left__lists__mypagelist__tag
        .contents-mypage__left__lists__mypagelist__tag__text
          ログアウト
        .contents-mypage__left__lists__mypagelist__tag__icon
          = icon('fas', 'angle-right',class:"angle")

app/views/mypages/card.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :card1
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "left"
    .contents-mypage__right
      .contents-mypage__right__title
        お支払い方法
      .contents-mypage__right__main
        クレジットカード一覧
        =link_to new_card_path,class:'login_button' do
          .contents-mypage__right__main__button
            =icon 'far','credit-card'
            クレジットカードを追加する
  .footer
    = render "shared/footer"

app/views/mypages/complete.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :complete
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__exhibition
        .contents-mypage__right__exhibition__title
          出品した商品
        .contents-mypage__right__exhibition__tab
          =link_to exhibition_mypages_path,class:"item_tab" do
            .contents-mypage__right__exhibition__tab__button
              出品中
          =link_to trans_mypages_path,class:"item_tab" do
            .contents-mypage__right__exhibition__tab__button
              取引中
          =link_to complete_mypages_path,class:"item_tab__active" do
            .contents-mypage__right__exhibition__tab__button
              売却済み
        .contents-mypage__right__exhibition__items
          -if @completes.present?
            -@completes.each do |item|
              =link_to item_path(item) do
                .contents-mypage__right__exhibition__items__item
                  .contents-mypage__right__exhibition__items__item__left
                    .contents-mypage__right__exhibition__items__item__left__image
                      =image_tag item.items_images[0].image_url ,class:"mypage_list_logo"
                    .contents-mypage__right__exhibition__items__item__left__detail
                      .contents-mypage__right__exhibition__items__item__left__detail__name
                        =item.name
                      .contents-mypage__right__exhibition__items__item__left__detail__status__complete
                        販売済
                  .contents-mypage__right__exhibition__items__item__icon
                    = icon('fas', 'angle-right',class:"angle_l")
          -else
            .contents-mypage__right__exhibition__items__empty
              =image_tag "/images/logo_gray.svg",class:"empty_logo"
              .contents-mypage__right__exhibition__items__empty__text
                売却済の商品がありません
        .contents-mypage__right__exhibition__page
          =link_to path_to_prev_page(@completes) do
            =icon "fas", "angle-left",class:"prev"
          =link_to path_to_next_page(@completes) do
            =icon "fas", "angle-right",class:"next"

app/views/mypages/exhibition.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :exhibition
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__exhibition
        .contents-mypage__right__exhibition__title
          出品した商品
        .contents-mypage__right__exhibition__tab
          =link_to exhibition_mypages_path,class:"item_tab__active" do
            .contents-mypage__right__exhibition__tab__button
              出品中
          =link_to trans_mypages_path,class:"item_tab" do
            .contents-mypage__right__exhibition__tab__button
              取引中
          =link_to complete_mypages_path,class:"item_tab" do
            .contents-mypage__right__exhibition__tab__button
              売却済み
        .contents-mypage__right__exhibition__items
          -if @exhibitions.present?
            -@exhibitions.each do |item|
              =link_to item_path(item) do
                .contents-mypage__right__exhibition__items__item
                  .contents-mypage__right__exhibition__items__item__left
                    .contents-mypage__right__exhibition__items__item__left__image
                      =image_tag item.items_images[0].image_url ,class:"mypage_list_logo"
                    .contents-mypage__right__exhibition__items__item__left__detail
                      .contents-mypage__right__exhibition__items__item__left__detail__name
                        =item.name
                      -if item.status=="exhibition"
                        .contents-mypage__right__exhibition__items__item__left__detail__status
                          出品中
                      -else
                        .contents-mypage__right__exhibition__items__item__left__detail__status__stop
                          公開停止中
                  .contents-mypage__right__exhibition__items__item__icon
                    = icon('fas', 'angle-right',class:"angle_l")
          -else
            .contents-mypage__right__exhibition__items__empty
              =image_tag "/images/logo_gray.svg",class:"empty_logo"
              .contents-mypage__right__exhibition__items__empty__text
                出品中の商品がありません
        .contents-mypage__right__exhibition__page
          =link_to path_to_prev_page(@exhibitions) do
            =icon "fas", "angle-left",class:"prev"
          =link_to path_to_next_page(@exhibitions) do
            =icon "fas", "angle-right",class:"next"

app/views/mypages/mypagelogout.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :logout
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "left"
    .contents-mypage__right
      .contents-mypage__right__main
        =link_to destroy_user_session_path ,method: :delete,class:"login_button" do
          .contents-logout__right__btn
            ログアウト
  .footer
    = render "shared/footer"

app/views/mypages/negotiate.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :negotiate
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__purchased
        .contents-mypage__right__purchased__title
          購入した商品
        .contents-mypage__right__purchased__tab
          =link_to negotiate_mypages_path,class:"item_tab2__active" do
            .contents-mypage__right__purchased__tab__button
              取引中
          =link_to purchased_mypages_path,class:"item_tab2" do
            .contents-mypage__right__purchased__tab__button
              過去の取引
        .contents-mypage__right__purchased__items
          -if @negotiate_items.present?
            -@negotiate_items.each do |item|
              =link_to item_path(item) do
                .contents-mypage__right__purchased__items__item
                  .contents-mypage__right__purchased__items__item__left
                    .contents-mypage__right__purchased__items__item__left__image
                      =image_tag item.items_images[0].image_url ,class:"mypage_list_logo"
                    .contents-mypage__right__purchased__items__item__left__detail
                      .contents-mypage__right__purchased__items__item__left__detail__name
                        =item.name
                      .contents-mypage__right__purchased__items__item__left__detail__status__complete
                        取引完了
                  .contents-mypage__right__purchased__items__item__icon
                    = icon('fas', 'angle-right',class:"angle_l")
          -else
            .contents-mypage__right__purchased__items__empty
              =image_tag "/images/logo_gray.svg",class:"empty_logo"
              .contents-mypage__right__purchased__items__empty__text
                取引中の商品がありません
        .contents-mypage__right__purchased__page
          =link_to path_to_prev_page(@negotiate_items) do
            =icon "fas", "angle-left",class:"prev"
          =link_to path_to_next_page(@negotiate_items) do
            =icon "fas", "angle-right",class:"next"

app/views/mypages/point.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :point
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__voucher
        .contents-mypage__right__voucher__title
          ポイント
        .contents-mypage__right__voucher__items
          .contents-mypage__right__voucher__items__item
            .contents-mypage__right__voucher__items__item__left
              .contents-mypage__right__voucher__items__item__left__detail
                .contents-mypage__right__voucher__items__item__left__detail__name
                  ポイント
                .contents-mypage__right__voucher__items__item__left__detail__price
                  =current_user.point.to_s(:delimited)
                  P

app/views/mypages/purchased.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :purchased
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__purchased
        .contents-mypage__right__purchased__title
          購入した商品
        .contents-mypage__right__purchased__tab
          =link_to negotiate_mypages_path,class:"item_tab2" do
            .contents-mypage__right__purchased__tab__button
              取引中
          =link_to purchased_mypages_path,class:"item_tab2__active" do
            .contents-mypage__right__purchased__tab__button
              過去の取引
        .contents-mypage__right__purchased__items
          -if @bought_items.present?
            -@bought_items.each do |item|
              =link_to item_path(item) do
                .contents-mypage__right__purchased__items__item
                  .contents-mypage__right__purchased__items__item__left
                    .contents-mypage__right__purchased__items__item__left__image
                      =image_tag item.items_images[0].image_url ,class:"mypage_list_logo"
                    .contents-mypage__right__purchased__items__item__left__detail
                      .contents-mypage__right__purchased__items__item__left__detail__name
                        「
                        =item.name
                        」を購入しました。取引が完了しました。
                      .contents-mypage__right__purchased__items__item__left__detail__status__complete
                        取引完了
                  .contents-mypage__right__purchased__items__item__icon
                    = icon('fas', 'angle-right',class:"angle_l")
          -else
            .contents-mypage__right__purchased__items__empty
              =image_tag "/images/logo_gray.svg",class:"empty_logo"
              .contents-mypage__right__purchased__items__empty__text
                購入した商品がありません
        .contents-mypage__right__purchased__page
          =link_to path_to_prev_page(@bought_items) do
            =icon "fas", "angle-left",class:"prev"
          =link_to path_to_next_page(@bought_items) do
            =icon "fas", "angle-right",class:"next"

app/views/mypages/sales.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :voucher
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__voucher
        .contents-mypage__right__voucher__title
          売り上げ
        .contents-mypage__right__voucher__items
          .contents-mypage__right__voucher__items__item
            .contents-mypage__right__voucher__items__item__left
              .contents-mypage__right__voucher__items__item__left__detail
                .contents-mypage__right__voucher__items__item__left__detail__name
                  現在の売上
                .contents-mypage__right__voucher__items__item__left__detail__price
                  =price_yen(@sales)
        .contents-mypage__right__voucher__items
          .contents-mypage__right__voucher__items__item
            .contents-mypage__right__voucher__items__item__left
              .contents-mypage__right__voucher__items__item__left__detail
                .contents-mypage__right__voucher__items__item__left__detail__name
                  ポイント
                .contents-mypage__right__voucher__items__item__left__detail__price
                  =current_user.point.to_s(:delimited)
                  P
          =link_to complete_mypages_path do
            .contents-mypage__right__voucher__items.sales
              .contents-mypage__right__voucher__items__item
                .contents-mypage__right__voucher__items__item__left
                  .contents-mypage__right__voucher__items__item__left__detail
                    .contents-mypage__right__voucher__items__item__left__detail__name
                      過去の売上履歴
                    .contents-mypage__right__voucher__items__item__left__detail__icon
                      = icon('fas', 'angle-right',class:"angle_l")

app/views/mypages/trans.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :trans
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__exhibition
        .contents-mypage__right__exhibition__title
          出品した商品
        .contents-mypage__right__exhibition__tab
          =link_to exhibition_mypages_path,class:"item_tab" do
            .contents-mypage__right__exhibition__tab__button
              出品中
          =link_to trans_mypages_path,class:"item_tab__active" do
            .contents-mypage__right__exhibition__tab__button
              取引中
          =link_to complete_mypages_path,class:"item_tab" do
            .contents-mypage__right__exhibition__tab__button
              売却済み
        .contents-mypage__right__exhibition__items
          -if @transes.present?
            -@transes.each do |item|
              =link_to item_path(item) do
                .contents-mypage__right__exhibition__items__item
                  .contents-mypage__right__exhibition__items__item__left
                    .contents-mypage__right__exhibition__items__item__left__image
                      =image_tag item.items_images[0].image_url ,class:"mypage_list_logo"
                    .contents-mypage__right__exhibition__items__item__left__detail
                      .contents-mypage__right__exhibition__items__item__left__detail__name
                        =item.name
                      .contents-mypage__right__exhibition__items__item__left__detail__status__trans
                        取引中
                  .contents-mypage__right__exhibition__items__item__icon
                    = icon('fas', 'angle-right',class:"angle_l")
          -else
            .contents-mypage__right__exhibition__items__empty
              =image_tag "/images/logo_gray.svg",class:"empty_logo"
              .contents-mypage__right__exhibition__items__empty__text
                取引中の商品がありません
        .contents-mypage__right__exhibition__page
          =link_to path_to_prev_page(@transes) do
            =icon "fas", "angle-left",class:"prev"
          =link_to path_to_next_page(@transes) do
            =icon "fas", "angle-right",class:"next"

app/views/mypages/voucher.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :voucher
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__voucher
        .contents-mypage__right__voucher__title
          クーポン
        .contents-mypage__right__voucher__items
          -if @vouchers.present?
            -@vouchers.each do |voucher|
              .contents-mypage__right__voucher__items__item
                .contents-mypage__right__voucher__items__item__left
                  .contents-mypage__right__voucher__items__item__left__detail
                    .contents-mypage__right__voucher__items__item__left__detail__name
                      =voucher.name
                    .contents-mypage__right__voucher__items__item__left__detail__price
                      =price_yen(voucher.price)