config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       registrations: "users/registrations",
                     }
  root "items#index"
  
  resources :mypages do
    collection do
      get :mypage
      get :mypagelogout
      get :card
      get :exhibition
      get :trans
      get :complete
      get :negotiate
      get :purchased
      get :voucher
      get :sales
      get :point
    end
  end
  resources :users do
    collection do
      get :profile
    end
  end
  resources :user_steps, only: [:create]
  resources :user_steps do
    collection do
      get "register1"
      get "register2"
      get "register3"
      get "register4"
      get "done"
    end
  end
  resources :cards, only: [:new, :show] do
    collection do
      post "pay", to: "cards#pay"
      post "delete", to: "cards#delete"
    end
  end
  resources :items do
    collection do
      post "pay", to: "items#pay"
      get "stop"
      get "exhibition"
      get :search
    end
    member do
      get :pay_comfirm
      post "pay", to: "items#pay"
    end
    resources :comments, only: :create
  end
  resources :categories do
    collection do
      get :category
      get :category_root
      get :category_child
      get :category_grandchild
    end
  end
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category
  has_many :items_images, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, presence: true, length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :condition, :delivery_charge_detail, :delivery_date, :price, presence: true
  validates :delivery_origin, presence: true
  validates :price, numericality: { greater_than: 299, less_than: 10000000 }
  validates :category_id, presence: true, numericality: { greater_than: 9, less_than: 31 }
  accepts_nested_attributes_for :items_images, allow_destroy: true
  enum status: {
    exhibition: 0, #出品
    trans: 1, #取引中
    stop: 2, #停止
    complete: 3, #売却済み
  }
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :delivery_origin

  def self.select_category(q)
    int_mat = q[:category_id_in].to_i
    if int_mat.between?(1,3)
      mat = Category.find(q[:category_id_in]).indirect_ids
      mat = mat.map(&:to_s)
      return mat
    elsif int_mat.between?(4,9)
      mat = Category.find(q[:category_id_in]).child_ids
      mat = mat.map(&:to_s)
      return mat
    elsif int_mat.between?(10,30)
      return int_mat.to_s
    else
      return ""
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:update, :show, :destroy, :edit]
  before_action :authenticate_user!, only: [:new, :show]
  before_action :set_card, only: [:pay_comfirm, :pay]
  before_action :set_category, except: [:create, :update, :destroy, :pay, :pay_comfirm]
  before_action :set_ransack, only: [:index, :show, :edit, :all, :search]

  def index
    @womens = Item.where(category_id: 10..16).where.not(status: "stop").limit(10).order(id: "DESC")
    @mens = Item.where(category_id: 17..23).where.not(status: "stop").limit(10).order(id: "DESC")
    @kids = Item.where(category_id: 24..30).where.not(status: "stop").limit(10).order(id: "DESC")
    @voucher = Voucher.find(1)
  end

  def new
    @item = Item.new
    @item.items_images.new
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
      end
    end
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      respond_to do |format|
        format.html { render :new }
        format.json
      end
    else
      set_category
      set_ransack
      render :new
    end
  end

  def edit
    @child_id = Category.find(@item.category_id).parent_id
    @children = Category.find(@item.category_id).parent.siblings
    @grand_children = Category.find(@item.category_id).siblings
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
      end
    end
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    session[:item] = @item
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    if @item.buyer.present?
      @buyer = User.find(@item.buyer)
    end
    if @item.voucher_id.present?
      @voucher = Voucher.find(@item.voucher_id)
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to item_path
    end
  end

  def pay_comfirm
    @item = Item.find(params[:id])
    Payjp.api_key = Rails.application.secrets.payjp_private_key
    customer = Payjp::Customer.retrieve(@card.customer_id)
    @default_card_information = customer.cards.retrieve(@card.card_id)
    @used_vouchers = UsedVoucherUser.where(user_id: current_user)
    @used_vouchers_mat = @used_vouchers.map { |record| record.voucher_id }
    @vouchers = Voucher.where.not(id: @used_vouchers_mat)
    session[:item] = @item
    @id = 0
    session[:point] = 0
    respond_to do |format|
      format.html
      format.json do
        @item = Item.find(params[:id])
        if (params[:flag] != nil)
          @id = params[:flag]
        end
        session[:point] = params[:point]
      end
    end
  end

  def pay
    @item = session[:item]
    id = @item["id"].to_s
    @item = Item.find(id)
    point = session[:point].to_i
    if (params[:id] != nil)
      @voucher = Voucher.find(params[:id])
      voucher_price = @voucher.price
      @item.voucher_id = @voucher.id
    else
      voucher_price = 0
    end
    @seller = User.find(@item.user_id)
    @seller.point = @seller.point + @item.price * 0.9
    @seller.save
    current_user.point = current_user.point - point
    current_user.save
    amount = @item.price - voucher_price - point
    if amount < 50
      amount = 50
    end
    Payjp.api_key = Rails.application.secrets.payjp_private_key
    Payjp::Charge.create(
      amount: amount,
      customer: @card.customer_id,
      currency: "jpy",
    )
    if (params[:id] != nil)
      @used_voucher_user = UsedVoucherUser.new(voucher_id: @voucher.id, user_id: current_user.id)
      @used_voucher_user.save
    end
    @item.complete!
    @item.buyer = current_user.id
    @item.used_point = point
    @item.updated_at = Time.now
    if @item.save
    else
      redirect_to pay_comfirm_items_path
    end
  end

  def stop
    @item = Item.find(params[:format])
    @item.status = "stop"
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def exhibition
    @item = Item.find(params[:format])
    @item.status = "exhibition"
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def search
    respond_to do |format|
      format.html
      format.json do
        @children = Category.find(params[:parent_id]).children
      end
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :condition, :delivery_charge_detail, :delivery_origin_id, :delivery_date, :price, :category_id, items_images_attributes: [:item_id, :image_url, :_destroy, :id]).merge(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_category
    @parents = Category.order("id ASC").limit(3)
  end

  def set_ransack
    if (params[:q] != nil && params[:q][:category_id_in] != nil)
      params[:q][:category_id_in] = params[:q][:category_id_in].to_i
      if (params[:q][:category_id_in].between?(1, 3))
        @parent_id = params[:q][:category_id_in].to_i
        @parent = Category.find(@parent_id)
        @children = @parent.children
      elsif (params[:q][:category_id_in].between?(4, 9))
        @parent_id = Category.find(params[:q][:category_id_in]).parent_id
        @child_id = params[:q][:category_id_in]
        @child = Category.find(@child_id)
        @children = Category.find(@child_id).siblings
        @grand_children = @child.children
      elsif (params[:q][:category_id_in].between?(10, 30))
        @parent_id = Category.find(params[:q][:category_id_in]).root_id
        @child_id = Category.find(params[:q][:category_id_in]).parent_id
        @grand_child_id = params[:q][:category_id_in]
        @children = Category.find(@child_id).siblings
        @grand_children = Category.find(@grand_child_id).siblings
      end
    end
    if params[:q] != nil
      params[:q][:category_id_in] = Item.select_category(params[:q])
      if params[:q][:name_cont_all] != nil
        @keyword = params[:q][:name_cont_all]
        params[:q][:name_cont_all] = params[:q][:name_cont_all].split(/[\p{blank}\s]+/)
      end
    end
    @search = Item.ransack(params[:q])
    @items = @search.result.where.not(status: "stop").page(params[:page]).per(16)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
  
  def price_yen(price)
    price = price.to_i
    price = "¥#{price.to_s(:delimited)}"
  end

  def fee(price)
    price=price.to_i
    price = price * 0.1
    price = "¥#{price.floor}"
  end

  def benefit(price)
    price=price.to_i
    tax = price * 0.1
    price = price-tax
    price = "¥#{price.floor}"
  end
end

app/views/items/_item.html.haml
-if @items.present?
  -@items.each do |item|
    %li.contents__all__item
      =link_to item_path(item) do
        .contents__all__item__image
          -if item.status=="complete"
            .contents__all__item__image__sold
            .contents__all__item__image__text
              SOLD
          = image_tag item.items_images[0].image_url.url,class: 'example'
          .contents__all__item__image__price
            =price_yen(item.price)
        .contents__all__item__name
          =item.name
-else
  .contents__all__empty
    =image_tag "/images/logo_gray.svg",class:"empty_logo"
    現在商品がございません

app/views/items/_modal.html.haml
#overlay
  #modalWindow
    .modal-message-box
      .modal-message-box_title
        %div 出品が完了しました。
      .modal-message-box_sentence
        %div あなたが出品した商品は「出品した商品一覧」からいつでも見ることができます。
    %button#modal-close-btn 続けて出品する 
    %button#delete-comformation-btn 商品ページへ

app/views/items/_product.html.haml
.content
  - item.images.each do |image|
    = image_tag image.src.url

app/views/items/index.html.haml
.html
  .header
    =render 'shared/header'
  .sell
    =link_to new_item_path ,class:'sell__button'do
      .sell__button__text
        出品
      .sell__button__img
        = icon('fas', 'camera',class:"camera")
  .voucher
    .voucher__name
      =@voucher.name
    .voucher__text
      配布中!
      %input{type: "hidden", value: @voucher.name, class: 'voucher_name' }
      %input{type: "hidden", value: @voucher.code, class: 'voucher_code' }
  .contents
    .contents_carousel
      %ul.carousel
        %li
          = image_tag src="/images/carousel2.png",class:"carousel_top_img"
        %li
          = image_tag src="/images/lumine_carousel.jpeg",class:"carousel_top_img"
    .contents__title
      %b人気のカテゴリー
      .contents__title__category
        =link_to category_root_categories_path(1),class:"contents__category__womens" do
          レディース
        =link_to category_root_categories_path(2),class:"contents__category__mens" do
          メンズ
        =link_to category_root_categories_path(3),class:"contents__category__kids" do
          子供
    .contents__new
      .contents__new__title
        %bレディース新着アイテム
      =link_to category_root_categories_path(1),class:"contents__new__more" do
        もっと見る
        =icon('fas', 'angle-right')
    %ul.contents__all
      = render 'wemens'
    .contents__new
      .contents__new__title
        %bメンズ新着アイテム
      =link_to category_root_categories_path(2),class:"contents__new__more" do
        もっと見る
        =icon('fas', 'angle-right')
    %ul.contents__all
      = render 'mens'
    .contents__new
      .contents__new__title
        %bキッズ新着アイテム
      =link_to category_root_categories_path(3),class:"contents__new__more" do
        もっと見る
        =icon('fas', 'angle-right')
    %ul.contents__all
      = render 'kids'
  .footer
    = render "shared/footer"

app/views/items/search.html.haml
.html
  .header
    =render 'shared/header'
  .sell
    =link_to new_item_path ,class:'sell__button'do
      .sell__button__text
        出品
      .sell__button__img
        = icon('fas', 'camera',class:"camera")
  .contents__searchscreen
    .contents__searchscreen__left
      =search_form_for(@search,url: search_items_path) do |f|
        .contents__searchscreen__left__sort
          = f.select :sorts, { '並び替え': 'id desc', '価格の安い順': 'price asc', '価格の高い順': 'price desc', '出品の古い順': 'updated_at asc', '出品の新しい順': 'updated_at desc' } , { selected: params[:q][:sorts] }, { onchange: 'this.form.submit()' ,class:"sort_form"}
        .contents__searchscreen__left__form
          .contents__searchscreen__left__form__label0
            詳細検索
          .contents__searchscreen__left__form__label1
            =icon "fas","plus",class:"search_icon"
            キーワードを追加する
          .contents__searchscreen__left__form__keyword
            =f.search_field :name_cont_all,{class:"detail_search_form",placeholder:"例）値下げ"}
          .contents__searchscreen__left__form__label
            =icon "fas","list-ul",class:"search_icon"
            カテゴリーを選択する
          .contents__searchscreen__left__form__category
            =f.collection_select :category_id_in, @parents, :id, :name,{include_blank: 'すべて',selected: @parent_id}, {class: "select-default", id: "parent-form"}
            -if(@children.present?)
              =f.select :category_id, options_for_select(@children.map{|c|[c[:name], c[:id], {'data-sample'=>c[:id]}]}, @child_id),{include_blank: 'すべて'}, {class: "select-default", id: "parent-form2"}
            -if(@grand_children.present?)
              =f.select :category_id, options_for_select(@grand_children.map{|c|[c[:name], c[:id], {'data-sample'=>c[:id]}]}, @grand_child_id),{include_blank: 'すべて'},{class: "select-default", id: "parent-form3"}
          .contents__searchscreen__left__form__label
            =icon "fas","coins",class:"search_icon"
            価格
          .contents__searchscreen__left__form__price
            %select{type: "text",class:"price_selecter",id:"price_selecter"}
              %option{value: "0"} 選択してください
              %option{value: "1"}300 ~ 1000
              %option{value: "2"}1000 ~ 5000
              %option{value: "3"}5000 ~ 10000
              %option{value: "4"}10000 ~ 30000
              %option{value: "5"}30000 ~ 50000
              %option{value: "6"}50000 ~
            =f.number_field :price_gteq,class:"price_field_lower",id:"price_field_lower",placeholder:"¥Min"
            &#126;
            =f.number_field :price_lteq,class:"price_field_upper",id:"price_field_upper",placeholder:"¥Max"
          .contents__searchscreen__left__form__label
            =icon "fas","star",class:"search_icon"
            商品の状態
          .contents__searchscreen__left__form__condition
            .contents__searchscreen__left__form__condition__box
              %input{type:"checkbox",class:"condition_box",id:"condition_box_all"}
              %label.condition_label
                すべて
            .contents__searchscreen__left__form__condition__box
              =f.check_box :condition_in,{multiple: true,class:"condition_box",id:"condition_box0"},"新品、未使用",nil
              =f.label "新品、未使用",class:"condition_label"
            .contents__searchscreen__left__form__condition__box
              =f.check_box :condition_in,{multiple: true,class:"condition_box",id:"condition_box1"},"未使用に近い",nil
              =f.label "未使用に近い",class:"condition_label"
            .contents__searchscreen__left__form__condition__box
              =f.check_box :condition_in,{multiple: true,class:"condition_box",id:"condition_box2"},"目立った傷や汚れなし",nil
              =f.label "目立った傷や汚れなし",class:"condition_label"
            .contents__searchscreen__left__form__condition__box
              =f.check_box :condition_in,{multiple: true,class:"condition_box",id:"condition_box3"},"やや傷や汚れあり",nil
              =f.label "やや傷や汚れあり",class:"condition_label"
            .contents__searchscreen__left__form__condition__box
              =f.check_box :condition_in,{multiple: true,class:"condition_box",id:"condition_box4"},"傷や汚れあり",nil
              =f.label "傷や汚れあり",class:"condition_label"
            .contents__searchscreen__left__form__condition__box
              =f.check_box :condition_in,{multiple: true,class:"condition_box",id:"condition_box5"},"全体的に状態が悪い",nil
              =f.label "全体的に状態が悪い",class:"condition_label"
          .contents__searchscreen__left__form__label
            =icon "fas","truck",class:"search_icon"
            配送料の負担
          .contents__searchscreen__left__form__charge
            .contents__searchscreen__left__form__charge__box
              %input{type:"checkbox",class:"charge_box",id:"charge_box_all"}
              %label.charge_label
                すべて
            .contents__searchscreen__left__form__charge__box
              =f.check_box :delivery_charge_detail_in,{multiple: true,class:"charge_box",id:"charge_box0"},"着払い（購入者負担）",nil
              =f.label "着払い(購入者負担)",class:"charge_label"
            .contents__searchscreen__left__form__charge__box
              =f.check_box :delivery_charge_detail_in,{multiple: true,class:"charge_box",id:"charge_box1"},"送料込み（出品者負担）",nil
              =f.label "送料込み(出品者負担)",class:"charge_label"
          .contents__searchscreen__left__form__label
            =icon "fas","shopping-cart",class:"search_icon"
            販売状況
          .contents__searchscreen__left__form__status
            .contents__searchscreen__left__form__status__box
              %input{type:"checkbox",class:"status_box",id:"status_box_all"}
              %label.status_label
                すべて
            .contents__searchscreen__left__form__status__box
              =f.check_box :status_in,{multiple: true,class:"status_box",id:"status_box0"},0,nil
              =f.label "販売中",class:"status_label"
            .contents__searchscreen__left__form__status__box
              =f.check_box :status_in,{multiple: true,class:"status_box",id:"status_box1"},3,nil
              =f.label "売り切れ",class:"status_label"
          .contents__searchscreen__left__form__button
            .contents__searchscreen__left__form__button__clear
              =f.submit "クリア",type: :reset,id:"search_reset"
            .contents__searchscreen__left__form__button__submit
              =f.submit "完了",id:"search_button"
    .contents__searchscreen__right
      .contents__searchscreen__right__search
        .contents__searchscreen__right__search__result
          .contents__searchscreen__right__search__result__num
            =@keyword
          .contents__searchscreen__right__search__result__text
            -if @keyword.present?
              の検索結果
            -else
              検索結果
        .contents__searchscreen__right__search__quantity
          =@items.offset_value
          &#045;
          =@items.offset_value + @items.length
          件表示
      %ul.contents__searchscreen__right__all
        = render 'item'
      .contents__searchscreen__right__page
        =paginate(@items)
  .footer
    = render "shared/footer"

app/views/items/show.html.haml
.html
  .header
    = render '/shared/header'
  -if (@item.user_id == current_user.id)
    .pan
      - breadcrumb :items,@item
      = render "layouts/breadcrumbs"
  .show-detail
    -if  ( @item.status=="complete" && @item.user_id==current_user.id )
      .show-detail_complete
        .show-detail_complete_left
          .show-detail_complete_left_title
            取引情報
            %table.trans-table
              %tr
                %th 商品
                %td
                  =@item.name
              %tr
                %th 送料
                %td 
                  =@item.delivery_charge_detail
              %tr
                %th 販売手数料
                %td 
                  =fee(@item.price)
              %tr
                %th 販売利益
                %td 
                  =benefit(@item.price)
              %tr
                %th 購入日時
                %td
                  =@item.updated_at.strftime("%Y-%m-%d %H:%M")
              %tr
                %th 商品ID
                %td 
                  =@item.id 
          .show-detail_complete_left_buyinfo
            .show-detail_complete_left_buyinfo_title
              購入情報
            .show-detail_complete_left_buyinfo_element
              .show-detail_complete_left_buyinfo_element_img
                = icon('fas', 'user',class:"user")
              .show-detail_complete_left_buyinfo_element_name
                =@buyer.nickname
              .show-detail_complete_left_buyinfo_element_arrow
                = icon('fas', 'angle-right',class:"angle")
        .show-detail_complete_right
          .show-detail_complete_right_title
            取引画面
          .show-detail_complete_right_info
            .show-detail_complete_right_info_element
              .show-detail_complete_right_info_element_mark
                = icon('fas', 'check',class:"checkmark")
              .show-detail_complete_right_info_element_text
                取引が完了しました
            .show-detail_complete_right_info_thanks
              このたびはメルカリのご利用ありがとうございました
          .show-detail_complete_right_delete.modal_button
            この商品を削除する
          =link_to "" ,item_path(@item),method: :delete,id:"delete_button"
    -else
      .show-detail_element
        .show-detail_element_title
          =@item.name
        .show-detail_element_main
          .show-detail_element_main_left
            .show-detail_element_main_left_img
              %div.slick1
                - @item.items_images.each do |item|
                  %div
                    %h3.img-element 
                      = image_tag item.image_url.url,class:"img_carusel"
            .show-detail_element_main_left_choice
              %div.slick2
                - @item.items_images.each do |item|
                  %div
                    %h3.img-element 
                      = image_tag item.image_url.url,class:"img_choice"
          .show-detail_element_main_right
            .show-detail_element_main_right_table
              %table.detail-table
                %tr
                  %th 出品者
                  %td
                    =@item.user.nickname
                %tr
                  %th カテゴリ
                  %td 
                    =@item.category.root.name
                    %br
                    >
                    =@item.category.parent.name
                    %br
                    >
                    =@item.category.name
                %tr
                  %th 商品の状態
                  %td 
                    =@item.condition
                %tr
                  %th 配送料の負担
                  %td 
                    =@item.delivery_charge_detail
                %tr
                  %th 配送元地域
                  %td
                    =@item.delivery_origin.name
                %tr
                  %th 発送日の目安
                  %td 
                    =@item.delivery_date 
        -if(@item.status=="complete" && @item.buyer==current_user.id && @item.used_point != 0 && @voucher.present?)
          .show-detail_element__voucher
            =price_yen(@item.price)
            　-　
            =price_yen(@voucher.price)
            (
            =@voucher.name
            )
            　-　
            =price_yen(@item.used_point)
            (
            ポイント
            )
            　=　
            =price_yen(@item.price-@item.used_point-@voucher.price)
          .show-detail_element__voucher__price
            =price_yen(@item.price-@item.used_point-@voucher.price)
            .show-detail_element__voucher__price__tax
              （税込）
            .show-detail_element__voucher__price__detail
              =@item.delivery_charge_detail
        -elsif(@item.status=="complete" && @item.buyer==current_user.id && @voucher.present?)
          .show-detail_element__voucher
            =price_yen(@item.price)
            　-　
            =price_yen(@voucher.price)
            (
            =@voucher.name
            )
            　=　
            =price_yen(@item.price-@voucher.price)
          .show-detail_element__voucher__price
            =price_yen(@item.price-@voucher.price)
            .show-detail_element__voucher__price__tax
              （税込）
            .show-detail_element__voucher__price__detail
              =@item.delivery_charge_detail
        -elsif(@item.status=="complete" && @item.buyer==current_user.id && @item.used_point != 0)
          .show-detail_element__voucher
            =price_yen(@item.price)
            　-　
            =price_yen(@item.used_point)
            (
            ポイント
            )
            　=　
            =price_yen(@item.price-@item.used_point)
          .show-detail_element__voucher__price
            =price_yen(@item.price-@item.used_point)
            .show-detail_element__voucher__price__tax
              （税込）
            .show-detail_element__voucher__price__detail
              =@item.delivery_charge_detail
        -else
          .show-detail_element_price
            .show-detail_element_price_yen
              =price_yen(@item.price)
            .show-detail_element_price_intax
              .show-detail_element_price_intax_text
                （税込）
            .show-detail_element_price_detail
              .show-detail_element_price_detail_text
                =@item.delivery_charge_detail
        .show-detail_element_description
          =simple_format(@item.description)
      .show-detail_botton
        -if user_signed_in?
          -if ( (@item.status=="exhibition" || @item.status=="trans") && @item.user_id==current_user.id )
            .show-detail_botton_edit
              =link_to edit_item_path(@item.id) do
                .show-detail_botton_edit_text
                  商品の編集
            .show-detail_botton_or
              or
            .show-detail_botton_stop
              =link_to stop_items_path(@item.id) do
                出品を一旦停止にする
            .show-detail_botton_delete.modal_button
              この商品を削除
            =link_to "" ,item_path(@item),method: :delete,id:"delete_button"
          -elsif(@item.status=="stop" && @item.user_id==current_user.id)
            .show-detail_botton_edit
              =link_to edit_item_path(@item.id) do
                .show-detail_botton_edit_text
                  商品の編集
            .show-detail_botton_or
              or
            .show-detail_botton_stop
              =link_to exhibition_items_path(@item.id) do
                出品を再開する
            .show-detail_botton_delete.modal_button.modal_button
              この商品を削除
              =link_to "" ,item_path(@item),method: :delete,id:"delete_button"
          -elsif (@item.status=="complete" && @item.user_id !=current_user.id && @item.buyer !=current_user.id)
            .show-detail_botton_soldout
              売り切れました
          -elsif (@item.status=="complete" && @item.user_id !=current_user.id && @item.buyer ==current_user.id)
            .show-detail_botton_soldout
              購入しました
          -else
            =link_to  pay_comfirm_item_path(@item.id) do
              .show-detail_botton_buy
                購入画面に進む
        -else
          =link_to pay_comfirm_item_path(@item.id) do
            .show-detail_botton_buy
              購入画面に進む 
    .show-detail_comment
      .show-detail_comment_rule
        相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
      .show-detail_comment_text
        - if current_user
          = form_for @comment,url: item_comments_path(@item.id) do |f|
            = f.text_area :comment, cols:"10",rows: "2",class:"input_comment"
            = f.submit "コメントする",class:"send_comment"
        - else
          %strong
            %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
      .show-detail_comment_all
        %h4 ＜コメント一覧＞
        - if @comments
          - @comments.each_with_index do |comment,num|
            .show-detail_comment_all_one-person{data:{"index":num}}
              -if comment.user.id!=current_user.id
                .show-detail_comment_all_one-person_img
                  -if comment.user.image.present?
                    = image_tag src=comment.user.image,class:"comment-userface"
                  -else
                    = image_tag src="/images/usericon.png",class:"comment-userface"
                  -if @item.user.id==comment.user.id
                    .seller 
                      出品者
                .show-detail_comment_all_one-person_elemnts
                  .show-detail_comment_all_one-person_elemnts_profile
                    = comment.user.nickname
                  .show-detail_comment_all_one-person_elemnts_text
                    .show-detail_comment_all_one-person_elemnts_text_right
                      = comment.comment
                    .show-detail_comment_all_one-person_elemnts_text_time
                      = "#{comment.created_at.strftime("%Y-%m-%d %H:%M")}投稿"
              -else
                .show-detail_comment_all_one-person_elemnts
                  .show-detail_comment_all_one-person_elemnts_profile
                    .show-detail_comment_all_one-person_elemnts_profile_nickname-right
                      = comment.user.nickname
                  .show-detail_comment_all_one-person_elemnts_text-left
                    .show-detail_comment_all_one-person_elemnts_text_left
                      = comment.comment
                    .show-detail_comment_all_one-person_elemnts_text_time
                      = "#{comment.created_at.strftime("%Y-%m-%d %H:%M")}投稿"
                .show-detail_comment_all_one-person_img
                  -if current_user.image.present?
                    = image_tag src=current_user.image,class:"comment-userface"
                  -else
                    = image_tag src="/images/usericon.png",class:"comment-userface"
                  -if @item.user.id==current_user.id
                    .seller 
                      出品者
  .footer
    = render '/shared/footer'
  .modal
    .modal__window
      .modal__window__text.modal_show
        .modal__window__text__title
          確認
        .modal__window__text__detail
          削除すると二度と復活できません。
          %br削除する代わりに停止することもできます。
          %br
          本当に削除しますか？
      .modal__window__button
        .modal__window__button__no
          キャンセル
        .modal__window__button__yes
          削除する