config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
                       omniauth_callbacks: "users/omniauth_callbacks",
                       registrations: "users/registrations",
                     }
  root "items#index"
  
  resources :mypages do
    collection do
      get :mypage
      get :mypagelogout
      get :card
      get :exhibition
      get :trans
      get :complete
      get :negotiate
      get :purchased
      get :voucher
      get :sales
      get :point
    end
  end
  resources :users do
    collection do
      get :profile
    end
  end
  resources :user_steps, only: [:create]
  resources :user_steps do
    collection do
      get "register1"
      get "register2"
      get "register3"
      get "register4"
      get "done"
    end
  end
  resources :cards, only: [:new, :show] do
    collection do
      post "pay", to: "cards#pay"
      post "delete", to: "cards#delete"
    end
  end
  resources :items do
    collection do
      post "pay", to: "items#pay"
      get "stop"
      get "exhibition"
      get :search
    end
    member do
      get :pay_comfirm
      post "pay", to: "items#pay"
    end
    resources :comments, only: :create
  end
  resources :categories do
    collection do
      get :category
      get :category_root
      get :category_child
      get :category_grandchild
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :customer_id,presence:true
  validates :card_id,presence:true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  require "payjp"
  before_action :set_card,only: %i[new delete show]
  before_action :set_category
  before_action :set_ransack,except:[:pay]

  def new
  end

  def pay #payjpとCardのデータベース作成を実施します。
    Payjp.api_key = Rails.application.secrets.payjp_private_key
    if params['payjp-token'].blank?
      redirect_to card_mypages_path
    else
      customer = Payjp::Customer.create(
      description: '登録テスト', #なくてもOK
      email: current_user.email, #なくてもOK
      card: params['payjp-token'],
      metadata: { user_id: current_user.id }
      ) #念の為metadataにuser_idを入れましたがなくてもOK
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to card_path(@card.id)
      else
        redirect_to pay_cards_path
      end
    end
  end

  def delete #PayjpとCardデータベースを削除します
    if @card.blank?
      redirect_to card_mypages_path
    else
      Payjp.api_key = Rails.application.secrets.payjp_private_key
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to card_mypages_path
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    if @card.blank?
      redirect_to card_mypages_path
    else
      Payjp.api_key = Rails.application.secrets.payjp_private_key
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  private

  def set_card
    @card = Card.find_by(user_id: current_user.id)
  end

  def set_category
    @parents = Category.order("id ASC").limit(3)
  end

  def set_ransack
    @search = Item.ransack(params[:q])
    @items = @search.result.page(params[:page]).per(16)
  end
end

app/views/cards/new.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :card2
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__title
        お支払い方法
      .contents-mypage__right__main
        = form_tag(pay_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
          %b.label
            カード番号
            .required
              必須
          .form
            = text_field_tag "number","", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number",class:"login_textfield"
          %b.label
            有効期限
            .required
              必須
          .form
            %select#exp_month{name: "exp_month", type: "text",class:"name_textfield"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月
          .form
            %select#exp_year{name: "exp_year", type: "text",class:"name_textfield"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年
          %b.label
            セキュリティコード
            .required
              必須
          .form
            = text_field_tag "cvc", "", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc",class:"login_textfield"
          #card_token
          = submit_tag "次へ進む", id: "token_submit",class:"login_button"
  .footer
    = render "shared/footer"

app/views/cards/show.html.haml
.html
  .hader
    = render "shared/header"
  .sell
    = render "shared/sell"
  .pan
    - breadcrumb :card3
    =render 'layouts/breadcrumbs'
  .contents-mypage
    .contents-mypage__left
      = render "mypages/left"
    .contents-mypage__right
      .contents-mypage__right__title
        お支払い方法
      .contents-mypage__right__main
        クレジットカード一覧
        .contents-mypage__right__main__card
          .contents-mypage__right__main__card__info
            = "**** **** **** " + @default_card_information.last4
            %br
            - exp_month = @default_card_information.exp_month.to_s
            - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
            = exp_month + " / " + exp_year
          .contents-mypage__right__main__card__delete
            = form_tag(delete_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
              %input{ type: "hidden", name: "card_id", value: "" }
              %button{class:"card_delete_button"}
                削除する
  .footer
    = render "shared/footer"